name: news
description: google news clone
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  test: ^1.14.2
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  dio_http_cache: ^0.2.6
  cached_network_image: ^2.1.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

